name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Build
      run: |
        ./gradlew nhterm:assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v3
      with:
        name: nhview
        path: ./nhterm/build/outputs/apk/debug
